services:
  app:
    image: laravel_app
    container_name: ${PROJECT_NAME}_app
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - laravel

  web:
    image: nginx:alpine
    container_name: ${PROJECT_NAME}_web
    volumes:
      - ./:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${PROJECT_NAME}.rule=Host(`${PROJECT_NAME}.localhost`)"
      - "traefik.http.services.${PROJECT_NAME}.loadbalancer.server.port=80"
    networks:
      - laravel

networks:
  laravel:
    external: true
